// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module saisie',
      items: [
        'module-saisie/saisir-collecte',
        'module-saisie/saisir-depot',
        'module-saisie/consulter-collecte-jour'
      ],
    },
    {
      type: 'category',
      label: 'Module analyse',
      items: [
        'module-analytique/consulter-historique-collecte',
        'module-analytique/consulter-depot',
        'module-analytique/chiffre-pour-declaration',
      ],
    },
    {
      type: 'category',
      label: 'Module paramètres',
      items: [
        'module-parametres/gestion-categories',
        'module-parametres/gestion-sites',
      ],
    },
    {
      type: 'category',
      label: 'Module administration',
      items: [
        'module-administration/gestion-utilisateurs',
      ],
    },
  ],
   
};

export default sidebars;
